source "https://rubygems.org"
gemspecs
gem "jekyll", "~> 4.3.0"
gem "jekyll-paginate"
gem "jekyll-sitemap"
gem "jekyll-gist"
gem "jekyll-feed"
gem "jekyll-include-cache"
gem "faraday-retry"
gem "tzinfo-data"
gem "tzinfo"
gem "csv"
gem "base64"
